---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    exclude_fingerprints:
    - 3b39f38c33cdc3b6dc57a5d8160f707b
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-81
ratings:
  paths:
  - "**.rb"
exclude_paths:
- features/
