version: '2'
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  rubocop:
    enabled: true
    channel: rubocop-0-80
  fixme:
    enabled: true
exclude_patterns:
- features/
