AllCops:
  TargetRubyVersion: 2.7
Layout/EmptyLineAfterMagicComment:
  AutoCorrect: true
Style/FrozenStringLiteralComment:
  AutoCorrect: true
Style/StringLiterals:
  AutoCorrect: true
Style/ClassAndModuleChildren:
  AutoCorrect: true
Style/HashSyntax:
  AutoCorrect: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true